In [1]:
import pandas as pd
import numpy as np

# TASK 1- Boston housing data
Show how Ridge and lasso help reduce overfitting

In [82]:
data = pd.read_csv(r'./HousingData.csv')
data.head()

FileNotFoundError: [Errno 2] No such file or directory: './HousingData.csv'

In [45]:
data = pd.read_csv('./winequalityN - winequalityN.csv')
data.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [7]:
data.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [46]:
data = data.dropna()

In [10]:
data.isnull().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [47]:
X = data.drop(columns='quality')
y = data.loc[:,'quality']

In [49]:
X =pd.get_dummies(X)

In [50]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [52]:
coef = lr.coef_

In [53]:
lr_df = pd.DataFrame({'feature' : X.columns,
             'coef' : coef})

In [23]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.1)
ridge.fit(X,y)

Ridge(alpha=0.1)

In [28]:
coef = ridge.coef_

In [31]:
pd.DataFrame({'coef':ridge.coef_.tolist()},
            index=[0.1],
            columns = X.columns)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type_white
0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
alphas = [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000]

coefs = []

for i in alphas:
    ridge = Ridge(alpha=i)
    ridge.fit(X,y)
    
    coefs.append(ridge.coef_.tolist())

In [65]:
arr = np.array(coefs)

In [66]:
df = pd.DataFrame(arr,
            columns = X.columns)
df['alpha'] = alphas
df.index= df['alpha']
df = df.drop(columns='alpha')

In [67]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type_red,type_white
alpha,,,,,,,,,,,,,
0.0001,0.082186,-1.508478,-0.079680,0.061502,-0.757033,0.004901,-0.001412,-99.606065,0.474837,0.719305,0.228399,0.179055,-0.179055
0.0010,0.061492,-1.524666,-0.087978,0.052050,-0.815545,0.005060,-0.001497,-74.744840,0.378294,0.686854,0.255395,0.152749,-0.152749
0.0100,0.017079,-1.559330,-0.105792,0.031763,-0.939750,0.005403,-0.001680,-21.381773,0.171114,0.617107,0.313350,0.096246,-0.096246
0.1000,0.001518,-1.570497,-0.112072,0.024640,-0.966684,0.005526,-0.001745,-2.629025,0.098818,0.591470,0.333833,0.075937,-0.075937
1.0000,-0.000052,-1.560570,-0.111930,0.023792,-0.828321,0.005563,-0.001763,-0.270909,0.094060,0.578173,0.337379,0.069222,-0.069222
10.0000,0.000747,-1.427976,-0.073155,0.023622,-0.347771,0.005786,-0.001860,-0.027888,0.106699,0.524288,0.340226,0.044071,-0.044071
100.0000,0.002771,-0.765705,0.077033,0.021892,-0.061122,0.006853,-0.002222,-0.003007,0.078780,0.322564,0.337437,-0.030940,0.030940
1000.0000,0.001721,-0.155674,0.042767,0.018169,-0.010390,0.007783,-0.002212,-0.000720,0.008153,0.060888,0.308710,-0.058203,0.058203
10000.0000,-0.014808,-0.021383,0.007291,0.006256,-0.002588,0.008164,-0.002252,-0.000266,-0.000527,0.004583,0.156098,-0.021598,0.021598

# Lasso

In [70]:
from sklearn.linear_model import Lasso

In [71]:
alphas = [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000]

coefs = []

for i in alphas:
    lasso = Lasso(alpha=i)
    lasso.fit(X,y)
    coefs.append(lasso.coef_.tolist())

In [74]:
coef_arr = np.array(coefs)
lasso_df = pd.DataFrame(coef_arr, columns=X.columns)

lasso_df['alpha'] = alphas
lasso_df.index= lasso_df['alpha']
lasso_df.drop(columns='alpha')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type_red,type_white
alpha,,,,,,,,,,,,,
0.0001,-0.000669,-1.566591,-0.108656,0.023637,-0.863137,0.005556,-0.001766,-0.0,0.088623,0.578840,0.337299,0.140841,-0.000000e+00
0.0010,-0.001090,-1.494434,-0.057961,0.023490,-0.000000,0.005704,-0.001885,-0.0,0.085414,0.498308,0.341698,0.091537,-7.399283e-19
0.0100,0.000000,-0.904334,0.000000,0.020193,-0.000000,0.006632,-0.002180,-0.0,0.000000,0.055501,0.332840,0.000000,-0.000000e+00
0.1000,-0.000000,-0.000000,0.000000,0.009628,-0.000000,0.007241,-0.001124,-0.0,-0.000000,0.000000,0.274237,-0.000000,0.000000e+00
1.0000,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,0.000598,-0.000465,-0.0,0.000000,0.000000,0.000000,-0.000000,0.000000e+00
10.0000,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,0.000000,-0.000000,-0.0,0.000000,0.000000,0.000000,-0.000000,0.000000e+00
100.0000,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,0.000000,-0.000000,-0.0,0.000000,0.000000,0.000000,-0.000000,0.000000e+00
1000.0000,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,0.000000,-0.000000,-0.0,0.000000,0.000000,0.000000,-0.000000,0.000000e+00
10000.0000,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,0.000000,-0.000000,-0.0,0.000000,0.000000,0.000000,-0.000000,0.000000e+00

- Observations
    * In ridge , as the value of alpha increases, the values of coefficients decreases and nears zero but never becomes zero
    * In lasso, as the value of alpha increases, the values of coefficients decreases and